spring:
  datasource:
    url: jdbc:h2:mem:graphltest
    username: admin
    password: admin
    driverClassName: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.H2Dialect
  graphql:
    graphiql:
      enabled: true
      path: /graphiql
